### ISSUE TITLE
Python API for 1.0

### ISSUE THREAD

**Issue by ryanmrichard** [NWChemEx/ParallelZone#75]
A 1.0 of ParallelZone requires the Python API to be finalized, decently performant, and unit tested. To that end I started PR: https://github.com/NWChemEx-Project/ParallelZone/pull/74. The aforementioned PR currently showcases several of the more general issues found on the [Python API project board](https://github.com/orgs/NWChemEx-Project/projects/19).

I specifically want to call out (sub bullets refer back to the #74):

- [ ] Import time (more general [issue](https://github.com/NWChemEx-Project/.github/issues/33))
  - The serial Python unit tests barely do anything and they take over 5x longer than the C++ tests
  - I haven't profiled, but I'm guessing this is import overhead, this issue should be updated if it's not
    - This is based on the times from Python `unittest` times being similar to the C++ times, but the final wall time is one to two orders of magnitude slower.
- [x] MPI overhead (more general [issue](https://github.com/NWChemEx-Project/NWChemEx/issues/85))
  - The MPI overhead is visible, but admittedly not too appreciable at this point (about half a second; C++ unit tests saw half that). It's possible that fleshing out more unit tests may add to to the overhead, or that we can ignore the overhead for ParallelZone. More profiling should be done.
- [ ] Import syntax (more general [issue](https://github.com/NWChemEx-Project/.github/issues/31))
  - A 1.0 requires us to finalize the API, so while a minor annoyance, this is critical for a release
- [ ] Auto-generated `__init__.py` file (more general [issue](https://github.com/NWChemEx-Project/.github/issues/38))
  - Same as above data point
- [ ] Unit tests of Python bindings of exposed C++
- [ ] Documentation of Python API.
